#!/usr/bin/bash
java -cp /opt/TEHO/unpacked/BOOT-INF/classes:/opt/TEHO/unpacked/BOOT-INF/lib/* -noverify -Dspring.jmx.enabled=false -XX:TieredStopAtLevel=1 -Dspring.profiles.active=production -Dspring.config.location=classpath:application.properties -Dspring.main.lazy-initialization=true -Dserver.port=33657 va.rit.teho.server.TehoApplication  &

processId=$(ps -ef | grep 'va.rit.teho.server.TehoApplication' | grep -v 'grep' | awk '{ printf $2 }')

/opt/TEHO/frontend/teho-web-0.1.0.AppImage --no-sandbox

kill $processId
