#!/usr/bin/bash
java -jar /opt/TEHO/teho-1.0-RELEASE.jar &

processId=$(ps -ef | grep 'teho-1.0-RELEASE.jar' | grep -v 'grep' | awk '{ printf $2 }')

/opt/TEHO/frontend/texo-web-0.1.0.AppImage --no-sandbox

kill $processId
